# Generated by Django 5.0.6 on 2024-07-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=244)),
                ('password', models.CharField(max_length=244)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=244)),
                ('title', models.CharField(max_length=244)),
                ('description', models.CharField(max_length=244)),
                ('status', models.CharField(max_length=244)),
                ('duedate', models.DateField()),
            ],
        ),
    ]
